// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClubRecordReqProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 target_account_id = 1;
    /**
     * <code>optional int64 target_account_id = 1;</code>
     */
    boolean hasTargetAccountId();
    /**
     * <code>optional int64 target_account_id = 1;</code>
     */
    long getTargetAccountId();

    // required int32 clubId = 2;
    /**
     * <code>required int32 clubId = 2;</code>
     */
    boolean hasClubId();
    /**
     * <code>required int32 clubId = 2;</code>
     */
    int getClubId();

    // optional int32 page = 3;
    /**
     * <code>optional int32 page = 3;</code>
     */
    boolean hasPage();
    /**
     * <code>optional int32 page = 3;</code>
     */
    int getPage();

    // optional int64 begin_time = 4;
    /**
     * <code>optional int64 begin_time = 4;</code>
     */
    boolean hasBeginTime();
    /**
     * <code>optional int64 begin_time = 4;</code>
     */
    long getBeginTime();

    // optional int64 end_time = 5;
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    long getEndTime();

    // optional int32 ruleId = 6;
    /**
     * <code>optional int32 ruleId = 6;</code>
     */
    boolean hasRuleId();
    /**
     * <code>optional int32 ruleId = 6;</code>
     */
    int getRuleId();

    // optional int32 totalSize = 7;
    /**
     * <code>optional int32 totalSize = 7;</code>
     *
     * <pre>
     *透传战绩总记录数
     * </pre>
     */
    boolean hasTotalSize();
    /**
     * <code>optional int32 totalSize = 7;</code>
     *
     * <pre>
     *透传战绩总记录数
     * </pre>
     */
    int getTotalSize();

    // optional int64 partnerId = 8;
    /**
     * <code>optional int64 partnerId = 8;</code>
     *
     * <pre>
     *合伙人Id
     * </pre>
     */
    boolean hasPartnerId();
    /**
     * <code>optional int64 partnerId = 8;</code>
     *
     * <pre>
     *合伙人Id
     * </pre>
     */
    long getPartnerId();

    // optional int32 onlyNotUpvote = 9;
    /**
     * <code>optional int32 onlyNotUpvote = 9;</code>
     *
     * <pre>
     * 0-全部 1-只未点赞的
     * </pre>
     */
    boolean hasOnlyNotUpvote();
    /**
     * <code>optional int32 onlyNotUpvote = 9;</code>
     *
     * <pre>
     * 0-全部 1-只未点赞的
     * </pre>
     */
    int getOnlyNotUpvote();
  }
  /**
   * Protobuf type {@code ClubRecordReqProto}
   *
   * <pre>
   *1223
   *3464534
   * </pre>
   */
  public static final class ClubRecordReqProto extends
      com.google.protobuf.GeneratedMessage
      implements ClubRecordReqProtoOrBuilder {
    // Use ClubRecordReqProto.newBuilder() to construct.
    private ClubRecordReqProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClubRecordReqProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClubRecordReqProto defaultInstance;
    public static ClubRecordReqProto getDefaultInstance() {
      return defaultInstance;
    }

    public ClubRecordReqProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClubRecordReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetAccountId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clubId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              page_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              beginTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              endTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ruleId_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              totalSize_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              partnerId_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              onlyNotUpvote_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test.internal_static_ClubRecordReqProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test.internal_static_ClubRecordReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Test.ClubRecordReqProto.class, Test.ClubRecordReqProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ClubRecordReqProto> PARSER =
        new com.google.protobuf.AbstractParser<ClubRecordReqProto>() {
      public ClubRecordReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClubRecordReqProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClubRecordReqProto> getParserForType() {
      return PARSER;
    }

    public interface HTEOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int32 aa = 1;
      /**
       * <code>optional int32 aa = 1;</code>
       */
      boolean hasAa();
      /**
       * <code>optional int32 aa = 1;</code>
       */
      int getAa();

      // optional int32 bb = 2;
      /**
       * <code>optional int32 bb = 2;</code>
       */
      boolean hasBb();
      /**
       * <code>optional int32 bb = 2;</code>
       */
      int getBb();

      // optional int32 cc = 3;
      /**
       * <code>optional int32 cc = 3;</code>
       */
      boolean hasCc();
      /**
       * <code>optional int32 cc = 3;</code>
       */
      int getCc();
    }
    /**
     * Protobuf type {@code ClubRecordReqProto.HTE}
     */
    public static final class HTE extends
        com.google.protobuf.GeneratedMessage
        implements HTEOrBuilder {
      // Use HTE.newBuilder() to construct.
      private HTE(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private HTE(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final HTE defaultInstance;
      public static HTE getDefaultInstance() {
        return defaultInstance;
      }

      public HTE getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private HTE(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                aa_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                bb_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                cc_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_ClubRecordReqProto_HTE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_ClubRecordReqProto_HTE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test.ClubRecordReqProto.HTE.class, Test.ClubRecordReqProto.HTE.Builder.class);
      }

      public static com.google.protobuf.Parser<HTE> PARSER =
          new com.google.protobuf.AbstractParser<HTE>() {
        public HTE parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HTE(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<HTE> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int32 aa = 1;
      public static final int AA_FIELD_NUMBER = 1;
      private int aa_;
      /**
       * <code>optional int32 aa = 1;</code>
       */
      public boolean hasAa() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 aa = 1;</code>
       */
      public int getAa() {
        return aa_;
      }

      // optional int32 bb = 2;
      public static final int BB_FIELD_NUMBER = 2;
      private int bb_;
      /**
       * <code>optional int32 bb = 2;</code>
       */
      public boolean hasBb() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 bb = 2;</code>
       */
      public int getBb() {
        return bb_;
      }

      // optional int32 cc = 3;
      public static final int CC_FIELD_NUMBER = 3;
      private int cc_;
      /**
       * <code>optional int32 cc = 3;</code>
       */
      public boolean hasCc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 cc = 3;</code>
       */
      public int getCc() {
        return cc_;
      }

      private void initFields() {
        aa_ = 0;
        bb_ = 0;
        cc_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, aa_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, bb_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, cc_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, aa_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, bb_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, cc_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Test.ClubRecordReqProto.HTE parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.HTE parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Test.ClubRecordReqProto.HTE parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Test.ClubRecordReqProto.HTE parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Test.ClubRecordReqProto.HTE prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ClubRecordReqProto.HTE}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements Test.ClubRecordReqProto.HTEOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Test.internal_static_ClubRecordReqProto_HTE_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Test.internal_static_ClubRecordReqProto_HTE_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Test.ClubRecordReqProto.HTE.class, Test.ClubRecordReqProto.HTE.Builder.class);
        }

        // Construct using Test.ClubRecordReqProto.HTE.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          aa_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          bb_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          cc_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Test.internal_static_ClubRecordReqProto_HTE_descriptor;
        }

        public Test.ClubRecordReqProto.HTE getDefaultInstanceForType() {
          return Test.ClubRecordReqProto.HTE.getDefaultInstance();
        }

        public Test.ClubRecordReqProto.HTE build() {
          Test.ClubRecordReqProto.HTE result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Test.ClubRecordReqProto.HTE buildPartial() {
          Test.ClubRecordReqProto.HTE result = new Test.ClubRecordReqProto.HTE(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.aa_ = aa_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.bb_ = bb_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.cc_ = cc_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Test.ClubRecordReqProto.HTE) {
            return mergeFrom((Test.ClubRecordReqProto.HTE)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Test.ClubRecordReqProto.HTE other) {
          if (other == Test.ClubRecordReqProto.HTE.getDefaultInstance()) return this;
          if (other.hasAa()) {
            setAa(other.getAa());
          }
          if (other.hasBb()) {
            setBb(other.getBb());
          }
          if (other.hasCc()) {
            setCc(other.getCc());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Test.ClubRecordReqProto.HTE parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Test.ClubRecordReqProto.HTE) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int32 aa = 1;
        private int aa_ ;
        /**
         * <code>optional int32 aa = 1;</code>
         */
        public boolean hasAa() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 aa = 1;</code>
         */
        public int getAa() {
          return aa_;
        }
        /**
         * <code>optional int32 aa = 1;</code>
         */
        public Builder setAa(int value) {
          bitField0_ |= 0x00000001;
          aa_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 aa = 1;</code>
         */
        public Builder clearAa() {
          bitField0_ = (bitField0_ & ~0x00000001);
          aa_ = 0;
          onChanged();
          return this;
        }

        // optional int32 bb = 2;
        private int bb_ ;
        /**
         * <code>optional int32 bb = 2;</code>
         */
        public boolean hasBb() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 bb = 2;</code>
         */
        public int getBb() {
          return bb_;
        }
        /**
         * <code>optional int32 bb = 2;</code>
         */
        public Builder setBb(int value) {
          bitField0_ |= 0x00000002;
          bb_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 bb = 2;</code>
         */
        public Builder clearBb() {
          bitField0_ = (bitField0_ & ~0x00000002);
          bb_ = 0;
          onChanged();
          return this;
        }

        // optional int32 cc = 3;
        private int cc_ ;
        /**
         * <code>optional int32 cc = 3;</code>
         */
        public boolean hasCc() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 cc = 3;</code>
         */
        public int getCc() {
          return cc_;
        }
        /**
         * <code>optional int32 cc = 3;</code>
         */
        public Builder setCc(int value) {
          bitField0_ |= 0x00000004;
          cc_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 cc = 3;</code>
         */
        public Builder clearCc() {
          bitField0_ = (bitField0_ & ~0x00000004);
          cc_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ClubRecordReqProto.HTE)
      }

      static {
        defaultInstance = new HTE(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ClubRecordReqProto.HTE)
    }

    public interface GGOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code ClubRecordReqProto.GG}
     */
    public static final class GG extends
        com.google.protobuf.GeneratedMessage
        implements GGOrBuilder {
      // Use GG.newBuilder() to construct.
      private GG(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private GG(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final GG defaultInstance;
      public static GG getDefaultInstance() {
        return defaultInstance;
      }

      public GG getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private GG(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_ClubRecordReqProto_GG_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_ClubRecordReqProto_GG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test.ClubRecordReqProto.GG.class, Test.ClubRecordReqProto.GG.Builder.class);
      }

      public static com.google.protobuf.Parser<GG> PARSER =
          new com.google.protobuf.AbstractParser<GG>() {
        public GG parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GG(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<GG> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Test.ClubRecordReqProto.GG parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.GG parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Test.ClubRecordReqProto.GG parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Test.ClubRecordReqProto.GG parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Test.ClubRecordReqProto.GG prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ClubRecordReqProto.GG}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements Test.ClubRecordReqProto.GGOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Test.internal_static_ClubRecordReqProto_GG_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Test.internal_static_ClubRecordReqProto_GG_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Test.ClubRecordReqProto.GG.class, Test.ClubRecordReqProto.GG.Builder.class);
        }

        // Construct using Test.ClubRecordReqProto.GG.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Test.internal_static_ClubRecordReqProto_GG_descriptor;
        }

        public Test.ClubRecordReqProto.GG getDefaultInstanceForType() {
          return Test.ClubRecordReqProto.GG.getDefaultInstance();
        }

        public Test.ClubRecordReqProto.GG build() {
          Test.ClubRecordReqProto.GG result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Test.ClubRecordReqProto.GG buildPartial() {
          Test.ClubRecordReqProto.GG result = new Test.ClubRecordReqProto.GG(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Test.ClubRecordReqProto.GG) {
            return mergeFrom((Test.ClubRecordReqProto.GG)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Test.ClubRecordReqProto.GG other) {
          if (other == Test.ClubRecordReqProto.GG.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Test.ClubRecordReqProto.GG parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Test.ClubRecordReqProto.GG) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ClubRecordReqProto.GG)
      }

      static {
        defaultInstance = new GG(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ClubRecordReqProto.GG)
    }

    private int bitField0_;
    // optional int64 target_account_id = 1;
    public static final int TARGET_ACCOUNT_ID_FIELD_NUMBER = 1;
    private long targetAccountId_;
    /**
     * <code>optional int64 target_account_id = 1;</code>
     */
    public boolean hasTargetAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 target_account_id = 1;</code>
     */
    public long getTargetAccountId() {
      return targetAccountId_;
    }

    // required int32 clubId = 2;
    public static final int CLUBID_FIELD_NUMBER = 2;
    private int clubId_;
    /**
     * <code>required int32 clubId = 2;</code>
     */
    public boolean hasClubId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 clubId = 2;</code>
     */
    public int getClubId() {
      return clubId_;
    }

    // optional int32 page = 3;
    public static final int PAGE_FIELD_NUMBER = 3;
    private int page_;
    /**
     * <code>optional int32 page = 3;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 page = 3;</code>
     */
    public int getPage() {
      return page_;
    }

    // optional int64 begin_time = 4;
    public static final int BEGIN_TIME_FIELD_NUMBER = 4;
    private long beginTime_;
    /**
     * <code>optional int64 begin_time = 4;</code>
     */
    public boolean hasBeginTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 begin_time = 4;</code>
     */
    public long getBeginTime() {
      return beginTime_;
    }

    // optional int64 end_time = 5;
    public static final int END_TIME_FIELD_NUMBER = 5;
    private long endTime_;
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 end_time = 5;</code>
     */
    public long getEndTime() {
      return endTime_;
    }

    // optional int32 ruleId = 6;
    public static final int RULEID_FIELD_NUMBER = 6;
    private int ruleId_;
    /**
     * <code>optional int32 ruleId = 6;</code>
     */
    public boolean hasRuleId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 ruleId = 6;</code>
     */
    public int getRuleId() {
      return ruleId_;
    }

    // optional int32 totalSize = 7;
    public static final int TOTALSIZE_FIELD_NUMBER = 7;
    private int totalSize_;
    /**
     * <code>optional int32 totalSize = 7;</code>
     *
     * <pre>
     *透传战绩总记录数
     * </pre>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 totalSize = 7;</code>
     *
     * <pre>
     *透传战绩总记录数
     * </pre>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    // optional int64 partnerId = 8;
    public static final int PARTNERID_FIELD_NUMBER = 8;
    private long partnerId_;
    /**
     * <code>optional int64 partnerId = 8;</code>
     *
     * <pre>
     *合伙人Id
     * </pre>
     */
    public boolean hasPartnerId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 partnerId = 8;</code>
     *
     * <pre>
     *合伙人Id
     * </pre>
     */
    public long getPartnerId() {
      return partnerId_;
    }

    // optional int32 onlyNotUpvote = 9;
    public static final int ONLYNOTUPVOTE_FIELD_NUMBER = 9;
    private int onlyNotUpvote_;
    /**
     * <code>optional int32 onlyNotUpvote = 9;</code>
     *
     * <pre>
     * 0-全部 1-只未点赞的
     * </pre>
     */
    public boolean hasOnlyNotUpvote() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 onlyNotUpvote = 9;</code>
     *
     * <pre>
     * 0-全部 1-只未点赞的
     * </pre>
     */
    public int getOnlyNotUpvote() {
      return onlyNotUpvote_;
    }

    private void initFields() {
      targetAccountId_ = 0L;
      clubId_ = 0;
      page_ = 0;
      beginTime_ = 0L;
      endTime_ = 0L;
      ruleId_ = 0;
      totalSize_ = 0;
      partnerId_ = 0L;
      onlyNotUpvote_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClubId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetAccountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clubId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, page_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, beginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, ruleId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, totalSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, partnerId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, onlyNotUpvote_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetAccountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clubId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, page_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, beginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, endTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ruleId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, totalSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, partnerId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, onlyNotUpvote_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Test.ClubRecordReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test.ClubRecordReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test.ClubRecordReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Test.ClubRecordReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Test.ClubRecordReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Test.ClubRecordReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Test.ClubRecordReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Test.ClubRecordReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Test.ClubRecordReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Test.ClubRecordReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Test.ClubRecordReqProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClubRecordReqProto}
     *
     * <pre>
     *1223
     *3464534
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Test.ClubRecordReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_ClubRecordReqProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_ClubRecordReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Test.ClubRecordReqProto.class, Test.ClubRecordReqProto.Builder.class);
      }

      // Construct using Test.ClubRecordReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetAccountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clubId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        beginTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        ruleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        totalSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        partnerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        onlyNotUpvote_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test.internal_static_ClubRecordReqProto_descriptor;
      }

      public Test.ClubRecordReqProto getDefaultInstanceForType() {
        return Test.ClubRecordReqProto.getDefaultInstance();
      }

      public Test.ClubRecordReqProto build() {
        Test.ClubRecordReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Test.ClubRecordReqProto buildPartial() {
        Test.ClubRecordReqProto result = new Test.ClubRecordReqProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetAccountId_ = targetAccountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clubId_ = clubId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.beginTime_ = beginTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ruleId_ = ruleId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.totalSize_ = totalSize_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.partnerId_ = partnerId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.onlyNotUpvote_ = onlyNotUpvote_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Test.ClubRecordReqProto) {
          return mergeFrom((Test.ClubRecordReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Test.ClubRecordReqProto other) {
        if (other == Test.ClubRecordReqProto.getDefaultInstance()) return this;
        if (other.hasTargetAccountId()) {
          setTargetAccountId(other.getTargetAccountId());
        }
        if (other.hasClubId()) {
          setClubId(other.getClubId());
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasBeginTime()) {
          setBeginTime(other.getBeginTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasRuleId()) {
          setRuleId(other.getRuleId());
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasPartnerId()) {
          setPartnerId(other.getPartnerId());
        }
        if (other.hasOnlyNotUpvote()) {
          setOnlyNotUpvote(other.getOnlyNotUpvote());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClubId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Test.ClubRecordReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Test.ClubRecordReqProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 target_account_id = 1;
      private long targetAccountId_ ;
      /**
       * <code>optional int64 target_account_id = 1;</code>
       */
      public boolean hasTargetAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 target_account_id = 1;</code>
       */
      public long getTargetAccountId() {
        return targetAccountId_;
      }
      /**
       * <code>optional int64 target_account_id = 1;</code>
       */
      public Builder setTargetAccountId(long value) {
        bitField0_ |= 0x00000001;
        targetAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 target_account_id = 1;</code>
       */
      public Builder clearTargetAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetAccountId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 clubId = 2;
      private int clubId_ ;
      /**
       * <code>required int32 clubId = 2;</code>
       */
      public boolean hasClubId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 clubId = 2;</code>
       */
      public int getClubId() {
        return clubId_;
      }
      /**
       * <code>required int32 clubId = 2;</code>
       */
      public Builder setClubId(int value) {
        bitField0_ |= 0x00000002;
        clubId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clubId = 2;</code>
       */
      public Builder clearClubId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clubId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 page = 3;
      private int page_ ;
      /**
       * <code>optional int32 page = 3;</code>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 page = 3;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional int32 page = 3;</code>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000004;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page = 3;</code>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        page_ = 0;
        onChanged();
        return this;
      }

      // optional int64 begin_time = 4;
      private long beginTime_ ;
      /**
       * <code>optional int64 begin_time = 4;</code>
       */
      public boolean hasBeginTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 begin_time = 4;</code>
       */
      public long getBeginTime() {
        return beginTime_;
      }
      /**
       * <code>optional int64 begin_time = 4;</code>
       */
      public Builder setBeginTime(long value) {
        bitField0_ |= 0x00000008;
        beginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 begin_time = 4;</code>
       */
      public Builder clearBeginTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        beginTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 end_time = 5;
      private long endTime_ ;
      /**
       * <code>optional int64 end_time = 5;</code>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 end_time = 5;</code>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 end_time = 5;</code>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000010;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 end_time = 5;</code>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 ruleId = 6;
      private int ruleId_ ;
      /**
       * <code>optional int32 ruleId = 6;</code>
       */
      public boolean hasRuleId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 ruleId = 6;</code>
       */
      public int getRuleId() {
        return ruleId_;
      }
      /**
       * <code>optional int32 ruleId = 6;</code>
       */
      public Builder setRuleId(int value) {
        bitField0_ |= 0x00000020;
        ruleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ruleId = 6;</code>
       */
      public Builder clearRuleId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ruleId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 totalSize = 7;
      private int totalSize_ ;
      /**
       * <code>optional int32 totalSize = 7;</code>
       *
       * <pre>
       *透传战绩总记录数
       * </pre>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 totalSize = 7;</code>
       *
       * <pre>
       *透传战绩总记录数
       * </pre>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>optional int32 totalSize = 7;</code>
       *
       * <pre>
       *透传战绩总记录数
       * </pre>
       */
      public Builder setTotalSize(int value) {
        bitField0_ |= 0x00000040;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalSize = 7;</code>
       *
       * <pre>
       *透传战绩总记录数
       * </pre>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        totalSize_ = 0;
        onChanged();
        return this;
      }

      // optional int64 partnerId = 8;
      private long partnerId_ ;
      /**
       * <code>optional int64 partnerId = 8;</code>
       *
       * <pre>
       *合伙人Id
       * </pre>
       */
      public boolean hasPartnerId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 partnerId = 8;</code>
       *
       * <pre>
       *合伙人Id
       * </pre>
       */
      public long getPartnerId() {
        return partnerId_;
      }
      /**
       * <code>optional int64 partnerId = 8;</code>
       *
       * <pre>
       *合伙人Id
       * </pre>
       */
      public Builder setPartnerId(long value) {
        bitField0_ |= 0x00000080;
        partnerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 partnerId = 8;</code>
       *
       * <pre>
       *合伙人Id
       * </pre>
       */
      public Builder clearPartnerId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        partnerId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 onlyNotUpvote = 9;
      private int onlyNotUpvote_ ;
      /**
       * <code>optional int32 onlyNotUpvote = 9;</code>
       *
       * <pre>
       * 0-全部 1-只未点赞的
       * </pre>
       */
      public boolean hasOnlyNotUpvote() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 onlyNotUpvote = 9;</code>
       *
       * <pre>
       * 0-全部 1-只未点赞的
       * </pre>
       */
      public int getOnlyNotUpvote() {
        return onlyNotUpvote_;
      }
      /**
       * <code>optional int32 onlyNotUpvote = 9;</code>
       *
       * <pre>
       * 0-全部 1-只未点赞的
       * </pre>
       */
      public Builder setOnlyNotUpvote(int value) {
        bitField0_ |= 0x00000100;
        onlyNotUpvote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 onlyNotUpvote = 9;</code>
       *
       * <pre>
       * 0-全部 1-只未点赞的
       * </pre>
       */
      public Builder clearOnlyNotUpvote() {
        bitField0_ = (bitField0_ & ~0x00000100);
        onlyNotUpvote_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ClubRecordReqProto)
    }

    static {
      defaultInstance = new ClubRecordReqProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ClubRecordReqProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClubRecordReqProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClubRecordReqProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClubRecordReqProto_HTE_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClubRecordReqProto_HTE_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClubRecordReqProto_GG_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClubRecordReqProto_GG_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test/test.proto\"\361\001\n\022ClubRecordReqProto" +
      "\022\031\n\021target_account_id\030\001 \001(\003\022\016\n\006clubId\030\002 " +
      "\002(\005\022\014\n\004page\030\003 \001(\005\022\022\n\nbegin_time\030\004 \001(\003\022\020\n" +
      "\010end_time\030\005 \001(\003\022\016\n\006ruleId\030\006 \001(\005\022\021\n\ttotal" +
      "Size\030\007 \001(\005\022\021\n\tpartnerId\030\010 \001(\003\022\025\n\ronlyNot" +
      "Upvote\030\t \001(\005\032)\n\003HTE\022\n\n\002aa\030\001 \001(\005\022\n\n\002bb\030\002 " +
      "\001(\005\022\n\n\002cc\030\003 \001(\005\032\004\n\002GG"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ClubRecordReqProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ClubRecordReqProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClubRecordReqProto_descriptor,
              new java.lang.String[] { "TargetAccountId", "ClubId", "Page", "BeginTime", "EndTime", "RuleId", "TotalSize", "PartnerId", "OnlyNotUpvote", });
          internal_static_ClubRecordReqProto_HTE_descriptor =
            internal_static_ClubRecordReqProto_descriptor.getNestedTypes().get(0);
          internal_static_ClubRecordReqProto_HTE_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClubRecordReqProto_HTE_descriptor,
              new java.lang.String[] { "Aa", "Bb", "Cc", });
          internal_static_ClubRecordReqProto_GG_descriptor =
            internal_static_ClubRecordReqProto_descriptor.getNestedTypes().get(1);
          internal_static_ClubRecordReqProto_GG_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClubRecordReqProto_GG_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
