// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.me.metadata.pb.test;

public final class TestMsgProto {
  private TestMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HelloProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 x = 1;
    /**
     * <code>optional int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    // optional string y = 2;
    /**
     * <code>optional string y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional string y = 2;</code>
     */
    String getY();
    /**
     * <code>optional string y = 2;</code>
     */
    com.google.protobuf.ByteString
        getYBytes();
  }
  /**
   * Protobuf type {@code test.HelloProto}
   */
  public static final class HelloProto extends
      com.google.protobuf.GeneratedMessage
      implements HelloProtoOrBuilder {
    // Use HelloProto.newBuilder() to construct.
    private HelloProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloProto defaultInstance;
    public static HelloProto getDefaultInstance() {
      return defaultInstance;
    }

    public HelloProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              y_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMsgProto.internal_static_test_HelloProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMsgProto.internal_static_test_HelloProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HelloProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<HelloProto> PARSER =
        new com.google.protobuf.AbstractParser<HelloProto>() {
      public HelloProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<HelloProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // optional string y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private Object y_;
    /**
     * <code>optional string y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string y = 2;</code>
     */
    public String getY() {
      Object ref = y_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          y_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string y = 2;</code>
     */
    public com.google.protobuf.ByteString
        getYBytes() {
      Object ref = y_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        y_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      x_ = 0;
      y_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getYBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getYBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HelloProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HelloProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HelloProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HelloProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HelloProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HelloProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HelloProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HelloProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HelloProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HelloProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HelloProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.HelloProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HelloProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMsgProto.internal_static_test_HelloProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMsgProto.internal_static_test_HelloProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HelloProto.class, Builder.class);
      }

      // Construct using com.me.metadata.pb.test.TestMsgProto.HelloProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMsgProto.internal_static_test_HelloProto_descriptor;
      }

      public HelloProto getDefaultInstanceForType() {
        return HelloProto.getDefaultInstance();
      }

      public HelloProto build() {
        HelloProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HelloProto buildPartial() {
        HelloProto result = new HelloProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HelloProto) {
          return mergeFrom((HelloProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HelloProto other) {
        if (other == HelloProto.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          bitField0_ |= 0x00000002;
          y_ = other.y_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HelloProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HelloProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 x = 1;
      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // optional string y = 2;
      private Object y_ = "";
      /**
       * <code>optional string y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string y = 2;</code>
       */
      public String getY() {
        Object ref = y_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          y_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string y = 2;</code>
       */
      public com.google.protobuf.ByteString
          getYBytes() {
        Object ref = y_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          y_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string y = 2;</code>
       */
      public Builder setY(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = getDefaultInstance().getY();
        onChanged();
        return this;
      }
      /**
       * <code>optional string y = 2;</code>
       */
      public Builder setYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.HelloProto)
    }

    static {
      defaultInstance = new HelloProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.HelloProto)
  }

  public interface TestReqProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string userName = 2;
    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string passWorld = 3;
    /**
     * <code>required string passWorld = 3;</code>
     */
    boolean hasPassWorld();
    /**
     * <code>required string passWorld = 3;</code>
     */
    String getPassWorld();
    /**
     * <code>required string passWorld = 3;</code>
     */
    com.google.protobuf.ByteString
        getPassWorldBytes();

    // repeated .test.HelloProto hellos = 4;
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    java.util.List<HelloProto>
        getHellosList();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    HelloProto getHellos(int index);
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    int getHellosCount();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    java.util.List<? extends HelloProtoOrBuilder>
        getHellosOrBuilderList();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    HelloProtoOrBuilder getHellosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code test.TestReqProto}
   *
   * <pre>
   *请求测试 协议号6666
   * </pre>
   */
  public static final class TestReqProto extends
      com.google.protobuf.GeneratedMessage
      implements TestReqProtoOrBuilder {
    // Use TestReqProto.newBuilder() to construct.
    private TestReqProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestReqProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestReqProto defaultInstance;
    public static TestReqProto getDefaultInstance() {
      return defaultInstance;
    }

    public TestReqProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              passWorld_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hellos_ = new java.util.ArrayList<HelloProto>();
                mutable_bitField0_ |= 0x00000008;
              }
              hellos_.add(input.readMessage(HelloProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hellos_ = java.util.Collections.unmodifiableList(hellos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMsgProto.internal_static_test_TestReqProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMsgProto.internal_static_test_TestReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestReqProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TestReqProto> PARSER =
        new com.google.protobuf.AbstractParser<TestReqProto>() {
      public TestReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestReqProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TestReqProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string passWorld = 3;
    public static final int PASSWORLD_FIELD_NUMBER = 3;
    private Object passWorld_;
    /**
     * <code>required string passWorld = 3;</code>
     */
    public boolean hasPassWorld() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string passWorld = 3;</code>
     */
    public String getPassWorld() {
      Object ref = passWorld_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passWorld_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passWorld = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPassWorldBytes() {
      Object ref = passWorld_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passWorld_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .test.HelloProto hellos = 4;
    public static final int HELLOS_FIELD_NUMBER = 4;
    private java.util.List<HelloProto> hellos_;
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public java.util.List<HelloProto> getHellosList() {
      return hellos_;
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public java.util.List<? extends HelloProtoOrBuilder>
        getHellosOrBuilderList() {
      return hellos_;
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public int getHellosCount() {
      return hellos_.size();
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public HelloProto getHellos(int index) {
      return hellos_.get(index);
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public HelloProtoOrBuilder getHellosOrBuilder(
        int index) {
      return hellos_.get(index);
    }

    private void initFields() {
      id_ = 0;
      userName_ = "";
      passWorld_ = "";
      hellos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassWorld()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPassWorldBytes());
      }
      for (int i = 0; i < hellos_.size(); i++) {
        output.writeMessage(4, hellos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPassWorldBytes());
      }
      for (int i = 0; i < hellos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, hellos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TestReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TestReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TestReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TestReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TestReqProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.TestReqProto}
     *
     * <pre>
     *请求测试 协议号6666
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TestReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMsgProto.internal_static_test_TestReqProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMsgProto.internal_static_test_TestReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestReqProto.class, Builder.class);
      }

      // Construct using com.me.metadata.pb.test.TestMsgProto.TestReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHellosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        passWorld_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (hellosBuilder_ == null) {
          hellos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          hellosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMsgProto.internal_static_test_TestReqProto_descriptor;
      }

      public TestReqProto getDefaultInstanceForType() {
        return TestReqProto.getDefaultInstance();
      }

      public TestReqProto build() {
        TestReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestReqProto buildPartial() {
        TestReqProto result = new TestReqProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passWorld_ = passWorld_;
        if (hellosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            hellos_ = java.util.Collections.unmodifiableList(hellos_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.hellos_ = hellos_;
        } else {
          result.hellos_ = hellosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestReqProto) {
          return mergeFrom((TestReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestReqProto other) {
        if (other == TestReqProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassWorld()) {
          bitField0_ |= 0x00000004;
          passWorld_ = other.passWorld_;
          onChanged();
        }
        if (hellosBuilder_ == null) {
          if (!other.hellos_.isEmpty()) {
            if (hellos_.isEmpty()) {
              hellos_ = other.hellos_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureHellosIsMutable();
              hellos_.addAll(other.hellos_);
            }
            onChanged();
          }
        } else {
          if (!other.hellos_.isEmpty()) {
            if (hellosBuilder_.isEmpty()) {
              hellosBuilder_.dispose();
              hellosBuilder_ = null;
              hellos_ = other.hellos_;
              bitField0_ = (bitField0_ & ~0x00000008);
              hellosBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHellosFieldBuilder() : null;
            } else {
              hellosBuilder_.addAllMessages(other.hellos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasUserName()) {

          return false;
        }
        if (!hasPassWorld()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestReqProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string userName = 2;
      private Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string passWorld = 3;
      private Object passWorld_ = "";
      /**
       * <code>required string passWorld = 3;</code>
       */
      public boolean hasPassWorld() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public String getPassWorld() {
        Object ref = passWorld_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passWorld_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPassWorldBytes() {
        Object ref = passWorld_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passWorld_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder setPassWorld(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWorld_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder clearPassWorld() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passWorld_ = getDefaultInstance().getPassWorld();
        onChanged();
        return this;
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder setPassWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWorld_ = value;
        onChanged();
        return this;
      }

      // repeated .test.HelloProto hellos = 4;
      private java.util.List<HelloProto> hellos_ =
        java.util.Collections.emptyList();
      private void ensureHellosIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hellos_ = new java.util.ArrayList<HelloProto>(hellos_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          HelloProto, HelloProto.Builder, HelloProtoOrBuilder> hellosBuilder_;

      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<HelloProto> getHellosList() {
        if (hellosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hellos_);
        } else {
          return hellosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public int getHellosCount() {
        if (hellosBuilder_ == null) {
          return hellos_.size();
        } else {
          return hellosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto getHellos(int index) {
        if (hellosBuilder_ == null) {
          return hellos_.get(index);
        } else {
          return hellosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder setHellos(
          int index, HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.set(index, value);
          onChanged();
        } else {
          hellosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder setHellos(
          int index, HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.set(index, builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.add(value);
          onChanged();
        } else {
          hellosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          int index, HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.add(index, value);
          onChanged();
        } else {
          hellosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.add(builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          int index, HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.add(index, builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addAllHellos(
          Iterable<? extends HelloProto> values) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          super.addAll(values, hellos_);
          onChanged();
        } else {
          hellosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder clearHellos() {
        if (hellosBuilder_ == null) {
          hellos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          hellosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder removeHellos(int index) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.remove(index);
          onChanged();
        } else {
          hellosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder getHellosBuilder(
          int index) {
        return getHellosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProtoOrBuilder getHellosOrBuilder(
          int index) {
        if (hellosBuilder_ == null) {
          return hellos_.get(index);  } else {
          return hellosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<? extends HelloProtoOrBuilder>
           getHellosOrBuilderList() {
        if (hellosBuilder_ != null) {
          return hellosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hellos_);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder addHellosBuilder() {
        return getHellosFieldBuilder().addBuilder(
            HelloProto.getDefaultInstance());
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder addHellosBuilder(
          int index) {
        return getHellosFieldBuilder().addBuilder(
            index, HelloProto.getDefaultInstance());
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<HelloProto.Builder>
           getHellosBuilderList() {
        return getHellosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          HelloProto, HelloProto.Builder, HelloProtoOrBuilder>
          getHellosFieldBuilder() {
        if (hellosBuilder_ == null) {
          hellosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              HelloProto, HelloProto.Builder, HelloProtoOrBuilder>(
                  hellos_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          hellos_ = null;
        }
        return hellosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:test.TestReqProto)
    }

    static {
      defaultInstance = new TestReqProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.TestReqProto)
  }

  public interface TestRspProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string userName = 2;
    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string passWorld = 3;
    /**
     * <code>required string passWorld = 3;</code>
     */
    boolean hasPassWorld();
    /**
     * <code>required string passWorld = 3;</code>
     */
    String getPassWorld();
    /**
     * <code>required string passWorld = 3;</code>
     */
    com.google.protobuf.ByteString
        getPassWorldBytes();

    // repeated .test.HelloProto hellos = 4;
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    java.util.List<HelloProto>
        getHellosList();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    HelloProto getHellos(int index);
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    int getHellosCount();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    java.util.List<? extends HelloProtoOrBuilder>
        getHellosOrBuilderList();
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    HelloProtoOrBuilder getHellosOrBuilder(
        int index);

    // optional string msg = 5;
    /**
     * <code>optional string msg = 5;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 5;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code test.TestRspProto}
   *
   * <pre>
   *返回测试 协议号6666
   * </pre>
   */
  public static final class TestRspProto extends
      com.google.protobuf.GeneratedMessage
      implements TestRspProtoOrBuilder {
    // Use TestRspProto.newBuilder() to construct.
    private TestRspProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestRspProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestRspProto defaultInstance;
    public static TestRspProto getDefaultInstance() {
      return defaultInstance;
    }

    public TestRspProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestRspProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              passWorld_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hellos_ = new java.util.ArrayList<HelloProto>();
                mutable_bitField0_ |= 0x00000008;
              }
              hellos_.add(input.readMessage(HelloProto.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hellos_ = java.util.Collections.unmodifiableList(hellos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestMsgProto.internal_static_test_TestRspProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestMsgProto.internal_static_test_TestRspProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestRspProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TestRspProto> PARSER =
        new com.google.protobuf.AbstractParser<TestRspProto>() {
      public TestRspProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestRspProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TestRspProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string passWorld = 3;
    public static final int PASSWORLD_FIELD_NUMBER = 3;
    private Object passWorld_;
    /**
     * <code>required string passWorld = 3;</code>
     */
    public boolean hasPassWorld() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string passWorld = 3;</code>
     */
    public String getPassWorld() {
      Object ref = passWorld_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passWorld_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passWorld = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPassWorldBytes() {
      Object ref = passWorld_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passWorld_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .test.HelloProto hellos = 4;
    public static final int HELLOS_FIELD_NUMBER = 4;
    private java.util.List<HelloProto> hellos_;
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public java.util.List<HelloProto> getHellosList() {
      return hellos_;
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public java.util.List<? extends HelloProtoOrBuilder>
        getHellosOrBuilderList() {
      return hellos_;
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public int getHellosCount() {
      return hellos_.size();
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public HelloProto getHellos(int index) {
      return hellos_.get(index);
    }
    /**
     * <code>repeated .test.HelloProto hellos = 4;</code>
     */
    public HelloProtoOrBuilder getHellosOrBuilder(
        int index) {
      return hellos_.get(index);
    }

    // optional string msg = 5;
    public static final int MSG_FIELD_NUMBER = 5;
    private Object msg_;
    /**
     * <code>optional string msg = 5;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      userName_ = "";
      passWorld_ = "";
      hellos_ = java.util.Collections.emptyList();
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassWorld()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPassWorldBytes());
      }
      for (int i = 0; i < hellos_.size(); i++) {
        output.writeMessage(4, hellos_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPassWorldBytes());
      }
      for (int i = 0; i < hellos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, hellos_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TestRspProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestRspProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestRspProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestRspProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestRspProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestRspProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TestRspProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TestRspProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TestRspProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TestRspProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TestRspProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.TestRspProto}
     *
     * <pre>
     *返回测试 协议号6666
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TestRspProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestMsgProto.internal_static_test_TestRspProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestMsgProto.internal_static_test_TestRspProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestRspProto.class, Builder.class);
      }

      // Construct using com.me.metadata.pb.test.TestMsgProto.TestRspProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHellosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        passWorld_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (hellosBuilder_ == null) {
          hellos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          hellosBuilder_.clear();
        }
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestMsgProto.internal_static_test_TestRspProto_descriptor;
      }

      public TestRspProto getDefaultInstanceForType() {
        return TestRspProto.getDefaultInstance();
      }

      public TestRspProto build() {
        TestRspProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestRspProto buildPartial() {
        TestRspProto result = new TestRspProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passWorld_ = passWorld_;
        if (hellosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            hellos_ = java.util.Collections.unmodifiableList(hellos_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.hellos_ = hellos_;
        } else {
          result.hellos_ = hellosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestRspProto) {
          return mergeFrom((TestRspProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestRspProto other) {
        if (other == TestRspProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassWorld()) {
          bitField0_ |= 0x00000004;
          passWorld_ = other.passWorld_;
          onChanged();
        }
        if (hellosBuilder_ == null) {
          if (!other.hellos_.isEmpty()) {
            if (hellos_.isEmpty()) {
              hellos_ = other.hellos_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureHellosIsMutable();
              hellos_.addAll(other.hellos_);
            }
            onChanged();
          }
        } else {
          if (!other.hellos_.isEmpty()) {
            if (hellosBuilder_.isEmpty()) {
              hellosBuilder_.dispose();
              hellosBuilder_ = null;
              hellos_ = other.hellos_;
              bitField0_ = (bitField0_ & ~0x00000008);
              hellosBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHellosFieldBuilder() : null;
            } else {
              hellosBuilder_.addAllMessages(other.hellos_);
            }
          }
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000010;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasUserName()) {

          return false;
        }
        if (!hasPassWorld()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestRspProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestRspProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string userName = 2;
      private Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string passWorld = 3;
      private Object passWorld_ = "";
      /**
       * <code>required string passWorld = 3;</code>
       */
      public boolean hasPassWorld() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public String getPassWorld() {
        Object ref = passWorld_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passWorld_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPassWorldBytes() {
        Object ref = passWorld_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passWorld_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder setPassWorld(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWorld_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder clearPassWorld() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passWorld_ = getDefaultInstance().getPassWorld();
        onChanged();
        return this;
      }
      /**
       * <code>required string passWorld = 3;</code>
       */
      public Builder setPassWorldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWorld_ = value;
        onChanged();
        return this;
      }

      // repeated .test.HelloProto hellos = 4;
      private java.util.List<HelloProto> hellos_ =
        java.util.Collections.emptyList();
      private void ensureHellosIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hellos_ = new java.util.ArrayList<HelloProto>(hellos_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          HelloProto, HelloProto.Builder, HelloProtoOrBuilder> hellosBuilder_;

      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<HelloProto> getHellosList() {
        if (hellosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hellos_);
        } else {
          return hellosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public int getHellosCount() {
        if (hellosBuilder_ == null) {
          return hellos_.size();
        } else {
          return hellosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto getHellos(int index) {
        if (hellosBuilder_ == null) {
          return hellos_.get(index);
        } else {
          return hellosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder setHellos(
          int index, HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.set(index, value);
          onChanged();
        } else {
          hellosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder setHellos(
          int index, HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.set(index, builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.add(value);
          onChanged();
        } else {
          hellosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          int index, HelloProto value) {
        if (hellosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHellosIsMutable();
          hellos_.add(index, value);
          onChanged();
        } else {
          hellosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.add(builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addHellos(
          int index, HelloProto.Builder builderForValue) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.add(index, builderForValue.build());
          onChanged();
        } else {
          hellosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder addAllHellos(
          Iterable<? extends HelloProto> values) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          super.addAll(values, hellos_);
          onChanged();
        } else {
          hellosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder clearHellos() {
        if (hellosBuilder_ == null) {
          hellos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          hellosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public Builder removeHellos(int index) {
        if (hellosBuilder_ == null) {
          ensureHellosIsMutable();
          hellos_.remove(index);
          onChanged();
        } else {
          hellosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder getHellosBuilder(
          int index) {
        return getHellosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProtoOrBuilder getHellosOrBuilder(
          int index) {
        if (hellosBuilder_ == null) {
          return hellos_.get(index);  } else {
          return hellosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<? extends HelloProtoOrBuilder>
           getHellosOrBuilderList() {
        if (hellosBuilder_ != null) {
          return hellosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hellos_);
        }
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder addHellosBuilder() {
        return getHellosFieldBuilder().addBuilder(
            HelloProto.getDefaultInstance());
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public HelloProto.Builder addHellosBuilder(
          int index) {
        return getHellosFieldBuilder().addBuilder(
            index, HelloProto.getDefaultInstance());
      }
      /**
       * <code>repeated .test.HelloProto hellos = 4;</code>
       */
      public java.util.List<HelloProto.Builder>
           getHellosBuilderList() {
        return getHellosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          HelloProto, HelloProto.Builder, HelloProtoOrBuilder>
          getHellosFieldBuilder() {
        if (hellosBuilder_ == null) {
          hellosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              HelloProto, HelloProto.Builder, HelloProtoOrBuilder>(
                  hellos_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          hellos_ = null;
        }
        return hellosBuilder_;
      }

      // optional string msg = 5;
      private Object msg_ = "";
      /**
       * <code>optional string msg = 5;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.TestRspProto)
    }

    static {
      defaultInstance = new TestRspProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.TestRspProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_HelloProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_HelloProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_TestReqProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_TestReqProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_TestRspProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_TestRspProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022\004test\"\"\n\nHelloProto\022\t\n\001x\030\001 " +
      "\001(\005\022\t\n\001y\030\002 \001(\t\"a\n\014TestReqProto\022\n\n\002id\030\001 \002" +
      "(\005\022\020\n\010userName\030\002 \002(\t\022\021\n\tpassWorld\030\003 \002(\t\022" +
      " \n\006hellos\030\004 \003(\0132\020.test.HelloProto\"n\n\014Tes" +
      "tRspProto\022\n\n\002id\030\001 \002(\005\022\020\n\010userName\030\002 \002(\t\022" +
      "\021\n\tpassWorld\030\003 \002(\t\022 \n\006hellos\030\004 \003(\0132\020.tes" +
      "t.HelloProto\022\013\n\003msg\030\005 \001(\tB\'\n\027com.me.meta" +
      "data.pb.testB\014TestMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_HelloProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_HelloProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_HelloProto_descriptor,
              new String[] { "X", "Y", });
          internal_static_test_TestReqProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_test_TestReqProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_TestReqProto_descriptor,
              new String[] { "Id", "UserName", "PassWorld", "Hellos", });
          internal_static_test_TestRspProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_test_TestRspProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_TestRspProto_descriptor,
              new String[] { "Id", "UserName", "PassWorld", "Hellos", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
