package com.me.metadata.db.entity;

import com.me.metadata.db.BaseEntity;

import java.util.Objects;

/**
 * @author Generated by database tools,  DO NOT EDIT!!!
 */
public class ClubEntityMemberEntity extends BaseEntity {

    /**
     * id of club
     */
    private int clubId;

    /**
     * member id
     */
    private long playerId;

    /**
     * 身份
     */
    private int identity;

    /**
     * 邀请者ID
     */
    private long inviterId;

    /**
     * 加入时间
     */
    private java.util.Date joinTime;

    /**
     * 加入后的总分数
     */
    private int score;

    /**
     * bc
     */
    private int bc;

    /**
     * gc
     */
    private int gc;

    /**
     * 备注
     */
    private String remarks;

    /**
     * partner
     */
    private long partnerId;

    /**
     * 
     */
    private int tireValue;

    /**
     * 
     */
    private int rebate;

    /**
     * 
     */
    private int rebateRatio;


    /**
     * id of club
     */
    public void setClubId(int clubId) {
        if (Objects.equals(this.clubId, clubId)) {
            return;
        }
        this.clubId = clubId;
        this.setUpdate(true);
    }

    /**
     * id of club
     */
    public int getClubId() {
        return this.clubId;
    }

    /**
     * member id
     */
    public void setPlayerId(long playerId) {
        if (Objects.equals(this.playerId, playerId)) {
            return;
        }
        this.playerId = playerId;
        this.setUpdate(true);
    }

    /**
     * member id
     */
    public long getPlayerId() {
        return this.playerId;
    }

    /**
     * 身份
     */
    public void setIdentity(int identity) {
        if (Objects.equals(this.identity, identity)) {
            return;
        }
        this.identity = identity;
        this.setUpdate(true);
    }

    /**
     * 身份
     */
    public int getIdentity() {
        return this.identity;
    }

    /**
     * 邀请者ID
     */
    public void setInviterId(long inviterId) {
        if (Objects.equals(this.inviterId, inviterId)) {
            return;
        }
        this.inviterId = inviterId;
        this.setUpdate(true);
    }

    /**
     * 邀请者ID
     */
    public long getInviterId() {
        return this.inviterId;
    }

    /**
     * 加入时间
     */
    public void setJoinTime(java.util.Date joinTime) {
        if (Objects.equals(this.joinTime, joinTime)) {
            return;
        }
        this.joinTime = joinTime;
        this.setUpdate(true);
    }

    /**
     * 加入时间
     */
    public java.util.Date getJoinTime() {
        return this.joinTime;
    }

    /**
     * 加入后的总分数
     */
    public void setScore(int score) {
        if (Objects.equals(this.score, score)) {
            return;
        }
        this.score = score;
        this.setUpdate(true);
    }

    /**
     * 加入后的总分数
     */
    public int getScore() {
        return this.score;
    }

    /**
     * bc
     */
    public void setBc(int bc) {
        if (Objects.equals(this.bc, bc)) {
            return;
        }
        this.bc = bc;
        this.setUpdate(true);
    }

    /**
     * bc
     */
    public int getBc() {
        return this.bc;
    }

    /**
     * gc
     */
    public void setGc(int gc) {
        if (Objects.equals(this.gc, gc)) {
            return;
        }
        this.gc = gc;
        this.setUpdate(true);
    }

    /**
     * gc
     */
    public int getGc() {
        return this.gc;
    }

    /**
     * 备注
     */
    public void setRemarks(String remarks) {
        if (Objects.equals(this.remarks, remarks)) {
            return;
        }
        this.remarks = remarks;
        this.setUpdate(true);
    }

    /**
     * 备注
     */
    public String getRemarks() {
        return this.remarks;
    }

    /**
     * partner
     */
    public void setPartnerId(long partnerId) {
        if (Objects.equals(this.partnerId, partnerId)) {
            return;
        }
        this.partnerId = partnerId;
        this.setUpdate(true);
    }

    /**
     * partner
     */
    public long getPartnerId() {
        return this.partnerId;
    }

    /**
     * 
     */
    public void setTireValue(int tireValue) {
        if (Objects.equals(this.tireValue, tireValue)) {
            return;
        }
        this.tireValue = tireValue;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getTireValue() {
        return this.tireValue;
    }

    /**
     * 
     */
    public void setRebate(int rebate) {
        if (Objects.equals(this.rebate, rebate)) {
            return;
        }
        this.rebate = rebate;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getRebate() {
        return this.rebate;
    }

    /**
     * 
     */
    public void setRebateRatio(int rebateRatio) {
        if (Objects.equals(this.rebateRatio, rebateRatio)) {
            return;
        }
        this.rebateRatio = rebateRatio;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getRebateRatio() {
        return this.rebateRatio;
    }

    @Override
    public ClubEntityMemberEntity clone() {
        ClubEntityMemberEntity entity = new ClubEntityMemberEntity();
        entity.clubId = this.clubId;
        entity.playerId = this.playerId;
        entity.identity = this.identity;
        entity.inviterId = this.inviterId;
        entity.joinTime = this.joinTime;
        entity.score = this.score;
        entity.bc = this.bc;
        entity.gc = this.gc;
        entity.remarks = this.remarks;
        entity.partnerId = this.partnerId;
        entity.tireValue = this.tireValue;
        entity.rebate = this.rebate;
        entity.rebateRatio = this.rebateRatio;
        return entity;
    }
}
