package com.me.metadata.db.entity;

import com.me.metadata.db.BaseEntity;

import java.util.Objects;

/**
 * @author Generated by database tools,  DO NOT EDIT!!!
 */
public class PlayerEntity extends BaseEntity {

    /**
     * 玩家ID
     */
    private long playerId;

    /**
     * 玩家昵称
     */
    private String playerName;

    /**
     * 0女1男
     */
    private int sex;

    /**
     * 头像
     */
    private String iconUrl;

    /**
     * 砖石数量
     */
    private int diamond;

    /**
     * 1微信 2PC
     */
    private int platform;

    /**
     * 金币数量
     */
    private int coin;

    /**
     * 注册时间
     */
    private java.util.Date registerTime;

    /**
     * 最近一次登录时间
     */
    private java.util.Date lastLoginTime;

    /**
     * 微信Unionid
     */
    private String wxUnionid;

    /**
     * 微信openID
     */
    private String wxOpenId;

    /**
     * 微信昵称
     */
    private String wxNickName;

    /**
     * wxcode
     */
    private String wxCode;

    /**
     * 自定义token,格式playerId|随机串|有效时间戳
     */
    private String customizeToken;

    /**
     *
     */
    private String registerIp;

    /**
     *
     */
    private String userName;

    /**
     *
     */
    private String passWord;


    /**
     * 玩家ID
     */
    public void setPlayerId(long playerId) {
        if (Objects.equals(this.playerId, playerId)) {
            return;
        }
        this.playerId = playerId;
        this.setUpdate(true);
    }

    /**
     * 玩家ID
     */
    public long getPlayerId() {
        return this.playerId;
    }

    /**
     * 玩家昵称
     */
    public void setPlayerName(String playerName) {
        if (Objects.equals(this.playerName, playerName)) {
            return;
        }
        this.playerName = playerName;
        this.setUpdate(true);
    }

    /**
     * 玩家昵称
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * 0女1男
     */
    public void setSex(int sex) {
        if (Objects.equals(this.sex, sex)) {
            return;
        }
        this.sex = sex;
        this.setUpdate(true);
    }

    /**
     * 0女1男
     */
    public int getSex() {
        return this.sex;
    }

    /**
     * 头像
     */
    public void setIconUrl(String iconUrl) {
        if (Objects.equals(this.iconUrl, iconUrl)) {
            return;
        }
        this.iconUrl = iconUrl;
        this.setUpdate(true);
    }

    /**
     * 头像
     */
    public String getIconUrl() {
        return this.iconUrl;
    }

    /**
     * 砖石数量
     */
    public void setDiamond(int diamond) {
        if (Objects.equals(this.diamond, diamond)) {
            return;
        }
        this.diamond = diamond;
        this.setUpdate(true);
    }

    /**
     * 砖石数量
     */
    public int getDiamond() {
        return this.diamond;
    }

    /**
     * 1微信 2PC
     */
    public void setPlatform(int platform) {
        if (Objects.equals(this.platform, platform)) {
            return;
        }
        this.platform = platform;
        this.setUpdate(true);
    }

    /**
     * 1微信 2PC
     */
    public int getPlatform() {
        return this.platform;
    }

    /**
     * 金币数量
     */
    public void setCoin(int coin) {
        if (Objects.equals(this.coin, coin)) {
            return;
        }
        this.coin = coin;
        this.setUpdate(true);
    }

    /**
     * 金币数量
     */
    public int getCoin() {
        return this.coin;
    }

    /**
     * 注册时间
     */
    public void setRegisterTime(java.util.Date registerTime) {
        if (Objects.equals(this.registerTime, registerTime)) {
            return;
        }
        this.registerTime = registerTime;
        this.setUpdate(true);
    }

    /**
     * 注册时间
     */
    public java.util.Date getRegisterTime() {
        return this.registerTime;
    }

    /**
     * 最近一次登录时间
     */
    public void setLastLoginTime(java.util.Date lastLoginTime) {
        if (Objects.equals(this.lastLoginTime, lastLoginTime)) {
            return;
        }
        this.lastLoginTime = lastLoginTime;
        this.setUpdate(true);
    }

    /**
     * 最近一次登录时间
     */
    public java.util.Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    /**
     * 微信Unionid
     */
    public void setWxUnionid(String wxUnionid) {
        if (Objects.equals(this.wxUnionid, wxUnionid)) {
            return;
        }
        this.wxUnionid = wxUnionid;
        this.setUpdate(true);
    }

    /**
     * 微信Unionid
     */
    public String getWxUnionid() {
        return this.wxUnionid;
    }

    /**
     * 微信openID
     */
    public void setWxOpenId(String wxOpenId) {
        if (Objects.equals(this.wxOpenId, wxOpenId)) {
            return;
        }
        this.wxOpenId = wxOpenId;
        this.setUpdate(true);
    }

    /**
     * 微信openID
     */
    public String getWxOpenId() {
        return this.wxOpenId;
    }

    /**
     * 微信昵称
     */
    public void setWxNickName(String wxNickName) {
        if (Objects.equals(this.wxNickName, wxNickName)) {
            return;
        }
        this.wxNickName = wxNickName;
        this.setUpdate(true);
    }

    /**
     * 微信昵称
     */
    public String getWxNickName() {
        return this.wxNickName;
    }

    /**
     * wxcode
     */
    public void setWxCode(String wxCode) {
        if (Objects.equals(this.wxCode, wxCode)) {
            return;
        }
        this.wxCode = wxCode;
        this.setUpdate(true);
    }

    /**
     * wxcode
     */
    public String getWxCode() {
        return this.wxCode;
    }

    /**
     * 自定义token,格式playerId|随机串|有效时间戳
     */
    public void setCustomizeToken(String customizeToken) {
        if (Objects.equals(this.customizeToken, customizeToken)) {
            return;
        }
        this.customizeToken = customizeToken;
        this.setUpdate(true);
    }

    /**
     * 自定义token,格式playerId|随机串|有效时间戳
     */
    public String getCustomizeToken() {
        return this.customizeToken;
    }

    /**
     *
     */
    public void setRegisterIp(String registerIp) {
        if (Objects.equals(this.registerIp, registerIp)) {
            return;
        }
        this.registerIp = registerIp;
        this.setUpdate(true);
    }

    /**
     *
     */
    public String getRegisterIp() {
        return this.registerIp;
    }

    /**
     *
     */
    public void setUserName(String userName) {
        if (Objects.equals(this.userName, userName)) {
            return;
        }
        this.userName = userName;
        this.setUpdate(true);
    }

    /**
     *
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     *
     */
    public void setPassWord(String passWord) {
        if (Objects.equals(this.passWord, passWord)) {
            return;
        }
        this.passWord = passWord;
        this.setUpdate(true);
    }

    /**
     *
     */
    public String getPassWord() {
        return this.passWord;
    }

    @Override
    public PlayerEntity clone() {
        PlayerEntity entity = new PlayerEntity();
        entity.playerId = this.playerId;
        entity.playerName = this.playerName;
        entity.sex = this.sex;
        entity.iconUrl = this.iconUrl;
        entity.diamond = this.diamond;
        entity.platform = this.platform;
        entity.coin = this.coin;
        entity.registerTime = this.registerTime;
        entity.lastLoginTime = this.lastLoginTime;
        entity.wxUnionid = this.wxUnionid;
        entity.wxOpenId = this.wxOpenId;
        entity.wxNickName = this.wxNickName;
        entity.wxCode = this.wxCode;
        entity.customizeToken = this.customizeToken;
        entity.registerIp = this.registerIp;
        entity.userName = this.userName;
        entity.passWord = this.passWord;
        return entity;
    }
}
