package com.me.metadata.db.entity;

import com.me.metadata.db.BaseEntity;

import java.util.Objects;

/**
 * @author Generated by database tools,  DO NOT EDIT!!!
 */
public class ClubEntity extends BaseEntity {

    /**
     * 
     */
    private int clubId;

    /**
     * 俱乐部名称
     */
    private String clubName;

    /**
     * 图标
     */
    private String clubIcon;

    /**
     * 群主
     */
    private long ownerId;

    /**
     * 创健时间
     */
    private java.util.Date createTime;

    /**
     * 公告
     */
    private String notice;

    /**
     * 俱乐部相关设置
     */
    private long settings;

    /**
     * 上次活跃时间
     */
    private java.util.Date lastActiveTime;

    /**
     * 
     */
    private byte[] applyJoinMsg;


    /**
     * 
     */
    public void setClubId(int clubId) {
        if (Objects.equals(this.clubId, clubId)) {
            return;
        }
        this.clubId = clubId;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getClubId() {
        return this.clubId;
    }

    /**
     * 俱乐部名称
     */
    public void setClubName(String clubName) {
        if (Objects.equals(this.clubName, clubName)) {
            return;
        }
        this.clubName = clubName;
        this.setUpdate(true);
    }

    /**
     * 俱乐部名称
     */
    public String getClubName() {
        return this.clubName;
    }

    /**
     * 图标
     */
    public void setClubIcon(String clubIcon) {
        if (Objects.equals(this.clubIcon, clubIcon)) {
            return;
        }
        this.clubIcon = clubIcon;
        this.setUpdate(true);
    }

    /**
     * 图标
     */
    public String getClubIcon() {
        return this.clubIcon;
    }

    /**
     * 群主
     */
    public void setOwnerId(long ownerId) {
        if (Objects.equals(this.ownerId, ownerId)) {
            return;
        }
        this.ownerId = ownerId;
        this.setUpdate(true);
    }

    /**
     * 群主
     */
    public long getOwnerId() {
        return this.ownerId;
    }

    /**
     * 创健时间
     */
    public void setCreateTime(java.util.Date createTime) {
        if (Objects.equals(this.createTime, createTime)) {
            return;
        }
        this.createTime = createTime;
        this.setUpdate(true);
    }

    /**
     * 创健时间
     */
    public java.util.Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 公告
     */
    public void setNotice(String notice) {
        if (Objects.equals(this.notice, notice)) {
            return;
        }
        this.notice = notice;
        this.setUpdate(true);
    }

    /**
     * 公告
     */
    public String getNotice() {
        return this.notice;
    }

    /**
     * 俱乐部相关设置
     */
    public void setSettings(long settings) {
        if (Objects.equals(this.settings, settings)) {
            return;
        }
        this.settings = settings;
        this.setUpdate(true);
    }

    /**
     * 俱乐部相关设置
     */
    public long getSettings() {
        return this.settings;
    }

    /**
     * 上次活跃时间
     */
    public void setLastActiveTime(java.util.Date lastActiveTime) {
        if (Objects.equals(this.lastActiveTime, lastActiveTime)) {
            return;
        }
        this.lastActiveTime = lastActiveTime;
        this.setUpdate(true);
    }

    /**
     * 上次活跃时间
     */
    public java.util.Date getLastActiveTime() {
        return this.lastActiveTime;
    }

    /**
     * 
     */
    public void setApplyJoinMsg(byte[] applyJoinMsg) {
        if (Objects.equals(this.applyJoinMsg, applyJoinMsg)) {
            return;
        }
        this.applyJoinMsg = applyJoinMsg;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public byte[] getApplyJoinMsg() {
        return this.applyJoinMsg;
    }

    @Override
    public ClubEntity clone() {
        ClubEntity entity = new ClubEntity();
        entity.clubId = this.clubId;
        entity.clubName = this.clubName;
        entity.clubIcon = this.clubIcon;
        entity.ownerId = this.ownerId;
        entity.createTime = this.createTime;
        entity.notice = this.notice;
        entity.settings = this.settings;
        entity.lastActiveTime = this.lastActiveTime;
        entity.applyJoinMsg = this.applyJoinMsg;
        return entity;
    }
}
