package com.me.metadata.db.entity;

import com.me.metadata.db.BaseEntity;

import java.util.Objects;

/**
 * @author Generated by database tools,  DO NOT EDIT!!!
 */
public class GameEntity extends BaseEntity {

    /**
     * 
     */
    private int gameId;

    /**
     * 
     */
    private String gameName;

    /**
     * 
     */
    private String iconUrl;

    /**
     * 1上线0下线-1:待开放
     */
    private int status;

    /**
     * 排序
     */
    private int order;

    /**
     * 路径
     */
    private String path;

    /**
     * 版本信息
     */
    private String version;

    /**
     * 局数:扣豆数|...
     */
    private String roundCfg;

    /**
     * 
     */
    private String gameUrl;

    /**
     * 
     */
    private int observe;


    /**
     * 
     */
    public void setGameId(int gameId) {
        if (Objects.equals(this.gameId, gameId)) {
            return;
        }
        this.gameId = gameId;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getGameId() {
        return this.gameId;
    }

    /**
     * 
     */
    public void setGameName(String gameName) {
        if (Objects.equals(this.gameName, gameName)) {
            return;
        }
        this.gameName = gameName;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public String getGameName() {
        return this.gameName;
    }

    /**
     * 
     */
    public void setIconUrl(String iconUrl) {
        if (Objects.equals(this.iconUrl, iconUrl)) {
            return;
        }
        this.iconUrl = iconUrl;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public String getIconUrl() {
        return this.iconUrl;
    }

    /**
     * 1上线0下线-1:待开放
     */
    public void setStatus(int status) {
        if (Objects.equals(this.status, status)) {
            return;
        }
        this.status = status;
        this.setUpdate(true);
    }

    /**
     * 1上线0下线-1:待开放
     */
    public int getStatus() {
        return this.status;
    }

    /**
     * 排序
     */
    public void setOrder(int order) {
        if (Objects.equals(this.order, order)) {
            return;
        }
        this.order = order;
        this.setUpdate(true);
    }

    /**
     * 排序
     */
    public int getOrder() {
        return this.order;
    }

    /**
     * 路径
     */
    public void setPath(String path) {
        if (Objects.equals(this.path, path)) {
            return;
        }
        this.path = path;
        this.setUpdate(true);
    }

    /**
     * 路径
     */
    public String getPath() {
        return this.path;
    }

    /**
     * 版本信息
     */
    public void setVersion(String version) {
        if (Objects.equals(this.version, version)) {
            return;
        }
        this.version = version;
        this.setUpdate(true);
    }

    /**
     * 版本信息
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * 局数:扣豆数|...
     */
    public void setRoundCfg(String roundCfg) {
        if (Objects.equals(this.roundCfg, roundCfg)) {
            return;
        }
        this.roundCfg = roundCfg;
        this.setUpdate(true);
    }

    /**
     * 局数:扣豆数|...
     */
    public String getRoundCfg() {
        return this.roundCfg;
    }

    /**
     * 
     */
    public void setGameUrl(String gameUrl) {
        if (Objects.equals(this.gameUrl, gameUrl)) {
            return;
        }
        this.gameUrl = gameUrl;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public String getGameUrl() {
        return this.gameUrl;
    }

    /**
     * 
     */
    public void setObserve(int observe) {
        if (Objects.equals(this.observe, observe)) {
            return;
        }
        this.observe = observe;
        this.setUpdate(true);
    }

    /**
     * 
     */
    public int getObserve() {
        return this.observe;
    }

    @Override
    public GameEntity clone() {
        GameEntity entity = new GameEntity();
        entity.gameId = this.gameId;
        entity.gameName = this.gameName;
        entity.iconUrl = this.iconUrl;
        entity.status = this.status;
        entity.order = this.order;
        entity.path = this.path;
        entity.version = this.version;
        entity.roundCfg = this.roundCfg;
        entity.gameUrl = this.gameUrl;
        entity.observe = this.observe;
        return entity;
    }
}
