transport:
  netty:
    soSndbuf: 12
    soRcvbuf: 23
    tcpNoDelay: true
    soKeepalive: true
    writeBufferWaterMarkLow: 1024
    writeBufferWaterMarkHigh: 2048


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jy_game?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    port: 6379
    host: localhost

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.me.metadata.db.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true